config/routes.rb
Rails.application.routes.draw do
  resources :dewormings
  resources :vaccines
  resources :pets
  get 'home/index'
  devise_for :owners, controllers: {registrations: 'owners/registrations'}
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
end

app/models/deworming.rb
class Deworming < ApplicationRecord
  belongs_to :pet
end

app/models/kind.rb
class Kind < ApplicationRecord
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :kind
  belongs_to :owner
  belongs_to :breed
end

app/models/vaccine.rb
class Vaccine < ApplicationRecord
  belongs_to :pet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
end

app/controllers/dewormings_controller.rb
class DewormingsController < ApplicationController
  before_action :set_deworming, only: [:show, :edit, :update, :destroy]

  # GET /dewormings
  # GET /dewormings.json
  def index
    @dewormings = Deworming.all
  end

  # GET /dewormings/1
  # GET /dewormings/1.json
  def show
  end

  # GET /dewormings/new
  def new
    @deworming = Deworming.new
  end

  # GET /dewormings/1/edit
  def edit
  end

  # POST /dewormings
  # POST /dewormings.json
  def create
    @deworming = Deworming.new(deworming_params)

    respond_to do |format|
      if @deworming.save
        format.html { redirect_to @deworming, notice: 'Deworming was successfully created.' }
        format.json { render :show, status: :created, location: @deworming }
      else
        format.html { render :new }
        format.json { render json: @deworming.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dewormings/1
  # PATCH/PUT /dewormings/1.json
  def update
    respond_to do |format|
      if @deworming.update(deworming_params)
        format.html { redirect_to @deworming, notice: 'Deworming was successfully updated.' }
        format.json { render :show, status: :ok, location: @deworming }
      else
        format.html { render :edit }
        format.json { render json: @deworming.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dewormings/1
  # DELETE /dewormings/1.json
  def destroy
    @deworming.destroy
    respond_to do |format|
      format.html { redirect_to dewormings_url, notice: 'Deworming was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deworming
      @deworming = Deworming.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deworming_params
      params.require(:deworming).permit(:pet_id, :deworming_date, :place)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
end

app/controllers/owners/sessions_controller.rb
# frozen_string_literal: true

class Owners::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/owners/unlocks_controller.rb
# frozen_string_literal: true

class Owners::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:kind_id, :owner_id, :name, :birth_day, :birth_month, :birth_year, :breed_id, :picture, :pet_registration_number)
    end
end

app/controllers/vaccines_controller.rb
class VaccinesController < ApplicationController
  before_action :set_vaccine, only: [:show, :edit, :update, :destroy]

  # GET /vaccines
  # GET /vaccines.json
  def index
    @vaccines = Vaccine.all
  end

  # GET /vaccines/1
  # GET /vaccines/1.json
  def show
  end

  # GET /vaccines/new
  def new
    @vaccine = Vaccine.new
  end

  # GET /vaccines/1/edit
  def edit
  end

  # POST /vaccines
  # POST /vaccines.json
  def create
    @vaccine = Vaccine.new(vaccine_params)

    respond_to do |format|
      if @vaccine.save
        format.html { redirect_to @vaccine, notice: 'Vaccine was successfully created.' }
        format.json { render :show, status: :created, location: @vaccine }
      else
        format.html { render :new }
        format.json { render json: @vaccine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vaccines/1
  # PATCH/PUT /vaccines/1.json
  def update
    respond_to do |format|
      if @vaccine.update(vaccine_params)
        format.html { redirect_to @vaccine, notice: 'Vaccine was successfully updated.' }
        format.json { render :show, status: :ok, location: @vaccine }
      else
        format.html { render :edit }
        format.json { render json: @vaccine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vaccines/1
  # DELETE /vaccines/1.json
  def destroy
    @vaccine.destroy
    respond_to do |format|
      format.html { redirect_to vaccines_url, notice: 'Vaccine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vaccine
      @vaccine = Vaccine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vaccine_params
      params.require(:vaccine).permit(:pet_id, :vaccine_date, :type_of_dose, :place)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/dewormings_helper.rb
module DewormingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/vaccines_helper.rb
module VaccinesHelper
end

app/views/dewormings/_form.html.erb
<%= form_with(model: deworming, local: true) do |form| %>
  <% if deworming.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deworming.errors.count, "error") %> prohibited this deworming from being saved:</h2>

      <ul>
      <% deworming.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pet_id %>
    <%= form.text_field :pet_id %>
  </div>

  <div class="field">
    <%= form.label :deworming_date %>
    <%= form.date_select :deworming_date %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dewormings/edit.html.erb
<h1>Editing Deworming</h1>

<%= render 'form', deworming: @deworming %>

<%= link_to 'Show', @deworming %> |
<%= link_to 'Back', dewormings_path %>

app/views/dewormings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dewormings</h1>

<table>
  <thead>
    <tr>
      <th>Pet</th>
      <th>Deworming date</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dewormings.each do |deworming| %>
      <tr>
        <td><%= deworming.pet %></td>
        <td><%= deworming.deworming_date %></td>
        <td><%= deworming.place %></td>
        <td><%= link_to 'Show', deworming %></td>
        <td><%= link_to 'Edit', edit_deworming_path(deworming) %></td>
        <td><%= link_to 'Destroy', deworming, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deworming', new_deworming_path %>

app/views/dewormings/new.html.erb
<h1>New Deworming</h1>

<%= render 'form', deworming: @deworming %>

<%= link_to 'Back', dewormings_path %>

app/views/dewormings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet:</strong>
  <%= @deworming.pet %>
</p>

<p>
  <strong>Deworming date:</strong>
  <%= @deworming.deworming_date %>
</p>

<p>
  <strong>Place:</strong>
  <%= @deworming.place %>
</p>

<%= link_to 'Edit', edit_deworming_path(@deworming) %> |
<%= link_to 'Back', dewormings_path %>

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :kind_id %>
    <%= form.text_field :kind_id %>
  </div>

  <div class="field">
    <%= form.label :owner_id %>
    <%= form.text_field :owner_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birth_day %>
    <%= form.number_field :birth_day %>
  </div>

  <div class="field">
    <%= form.label :birth_month %>
    <%= form.number_field :birth_month %>
  </div>

  <div class="field">
    <%= form.label :birth_year %>
    <%= form.number_field :birth_year %>
  </div>

  <div class="field">
    <%= form.label :breed_id %>
    <%= form.text_field :breed_id %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="field">
    <%= form.label :pet_registration_number %>
    <%= form.text_field :pet_registration_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Kind</th>
      <th>Owner</th>
      <th>Name</th>
      <th>Birth day</th>
      <th>Birth month</th>
      <th>Birth year</th>
      <th>Breed</th>
      <th>Picture</th>
      <th>Pet registration number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.kind %></td>
        <td><%= pet.owner %></td>
        <td><%= pet.name %></td>
        <td><%= pet.birth_day %></td>
        <td><%= pet.birth_month %></td>
        <td><%= pet.birth_year %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.picture %></td>
        <td><%= pet.pet_registration_number %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kind:</strong>
  <%= @pet.kind %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @pet.owner %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Birth day:</strong>
  <%= @pet.birth_day %>
</p>

<p>
  <strong>Birth month:</strong>
  <%= @pet.birth_month %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @pet.birth_year %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @pet.picture %>
</p>

<p>
  <strong>Pet registration number:</strong>
  <%= @pet.pet_registration_number %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/vaccines/_form.html.erb
<%= form_with(model: vaccine, local: true) do |form| %>
  <% if vaccine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vaccine.errors.count, "error") %> prohibited this vaccine from being saved:</h2>

      <ul>
      <% vaccine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pet_id %>
    <%= form.text_field :pet_id %>
  </div>

  <div class="field">
    <%= form.label :vaccine_date %>
    <%= form.date_select :vaccine_date %>
  </div>

  <div class="field">
    <%= form.label :type_of_dose %>
    <%= form.text_field :type_of_dose %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vaccines/edit.html.erb
<h1>Editing Vaccine</h1>

<%= render 'form', vaccine: @vaccine %>

<%= link_to 'Show', @vaccine %> |
<%= link_to 'Back', vaccines_path %>

app/views/vaccines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vaccines</h1>

<table>
  <thead>
    <tr>
      <th>Pet</th>
      <th>Vaccine date</th>
      <th>Type of dose</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vaccines.each do |vaccine| %>
      <tr>
        <td><%= vaccine.pet %></td>
        <td><%= vaccine.vaccine_date %></td>
        <td><%= vaccine.type_of_dose %></td>
        <td><%= vaccine.place %></td>
        <td><%= link_to 'Show', vaccine %></td>
        <td><%= link_to 'Edit', edit_vaccine_path(vaccine) %></td>
        <td><%= link_to 'Destroy', vaccine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vaccine', new_vaccine_path %>

app/views/vaccines/new.html.erb
<h1>New Vaccine</h1>

<%= render 'form', vaccine: @vaccine %>

<%= link_to 'Back', vaccines_path %>

app/views/vaccines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet:</strong>
  <%= @vaccine.pet %>
</p>

<p>
  <strong>Vaccine date:</strong>
  <%= @vaccine.vaccine_date %>
</p>

<p>
  <strong>Type of dose:</strong>
  <%= @vaccine.type_of_dose %>
</p>

<p>
  <strong>Place:</strong>
  <%= @vaccine.place %>
</p>

<%= link_to 'Edit', edit_vaccine_path(@vaccine) %> |
<%= link_to 'Back', vaccines_path %>